version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fitnessai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: gunicorn backend.app.main:app -c infra/gunicorn_conf.py
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@db:5432/fitnessai
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: virtual-trainer
      S3_REGION: us-east-1
      S3_USE_SSL: "false"
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"

  worker:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: python -m backend.worker.worker
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@db:5432/fitnessai
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: virtual-trainer
      S3_REGION: us-east-1
      S3_USE_SSL: "false"
    depends_on:
      - db
      - redis
      - minio

volumes:
  pgdata:
  minio:
